### PR TITLE
[#1402] Scaffold frontend-react/ — React 19 + Tailwind v4 + shadcn/ui

### LINKED ISSUE #1402: [FE] Scaffold `frontend-react/` (Vite + TS + Tailwind v4 + shadcn/ui + Vitest + Playwright + go:embed)
Parent epic: **#1397**.

## Goal

Stand up the new React frontend skeleton at `frontend-react/`, mirroring the stack of the design mock 1:1, plus the production-grade additions the mock lacks (router, data layer, i18n, tests). This issue ships the *empty house*; subsequent issues fill in features.

### Tooling

- Vite 7 + `@vitejs/plugin-react` + Tailwind v4 via `@tailwindcss/vite`.
- TypeScript strict, `verbatimModuleSyntax`, ES2022, JSX `react-jsx`. Path alias `@ → ./src`.
- shadcn/ui copy-in (`components.json` mirrors the mock: `style: "new-york"`, `baseColor: "neutral"`, `cssVariables: true`). Copy the same primitives the mock uses; reject `@base-ui/react` (lock to Radix defaults — see mock-repo issue).
- `lucide-react` for icons.
- `class-variance-authority`, `clsx`, `tailwind-merge`.
- `react-hook-form` + `@hookform/resolvers` + `zod`.
- `sonner` for toasts.
- ESLint flat config + `@typescript-eslint`, `eslint-plugin-react`, `eslint-plugin-react-hooks`, `eslint-plugin-jsx-a11y`, `eslint-plugin-tailwindcss`.
- Prettier.
- Vitest + `@testing-library/react` + `@testing-library/user-event` + `jsdom` + `jest-axe`.
- Playwright (config to share with existing `e2e/` harness — to be wired in the e2e port issue).
- `vitest.config.ts` with coverage gates (text, json, html).

### Structure

```
frontend-react/
├── package.json, vite.config.ts, tsconfig*.json, eslint.config.js, .prettierrc
├── index.html (NO Bolt og:image; "Inventario" title)
├── frontend.go         //go:build with_frontend; //go:embed all:dist
├── public/             logo + favicon
└── src/
    ├── app/            App.tsx, providers
    ├── pages/          (empty placeholders)
    ├── features/
    ├── components/ui/  shadcn copy-in
    ├── components/     project components (later)
    ├── lib/            cn, env, http (later)
    ├── hooks/
    ├── i18n/           react-i18next config (later issue) — bootstrap dir only
    ├── types/          OpenAPI generated dir (later)
    ├── test/           setup.ts, msw handlers (later)
    └── index.css       @theme tokens copied from mock
```

### Make / Docker / CI

- `Makefile`: `build-frontend-react`, `lint-frontend-react`, `test-frontend-react`, `test-e2e` (added to combined targets).
- `Dockerfile`: builds both bundles during the migration window.
- CI: lint + typecheck + unit tests + build for `frontend-react/` on every PR that touches it.

### No-Bolt artifacts

- No `.bolt/` directory.
- `index.html` `<title>Inventario</title>`, no bolt og:image.
- README explains the project, not "Open in Bolt".

## Acceptance criteria

- [ ] `npm install && npm run build` in `frontend-react/` produces `dist/` with React 19 bundle.
- [ ] `npm run typecheck`, `npm run lint`, `npm run test` all pass on the empty skeleton.
- [ ] A "Hello world" page loads at `/` when running `dev` server.
- [ ] `INVENTARIO_FRONTEND=new` Go server (after the BE env-var issue) serves the React bundle.
- [ ] `tsconfig.json` strict; eslint flat config has the listed plugins; Prettier integrated.
- [ ] No Bolt.new artifacts.
- [ ] Make targets work: `make lint-frontend-react`, `make test-frontend-react`, `make build-frontend-react`.
- [ ] Coverage report generated on `npm run test:coverage`.
- [ ] CI runs the new targets.

## Test plan

- Unit: a single hello-world component test that renders + asserts a string.
- Smoke: `vite build` succeeds, `vite preview` serves.
- Embed: Go integration test serves `dist/index.html` with the right title.

## Files likely touched

- `frontend-react/**` (new)
- `Makefile`
- `Dockerfile`
- `.github/workflows/*.yml`
- `frontend-react/frontend.go` (companion to the BE env-var issue)

## Cross-refs

- Sibling: BE env-var issue.
- Blocks every FE feature issue.

### PR DESCRIPTION
**Pull request by denisvmedia**
Closes #1402. Parent epic: #1397.

## Summary

Empty-house React frontend scaffold for the rewrite tracked in epic #1397. The new tree at `frontend-react/` coexists with the legacy Vue tree at `frontend/` until parity is reached; runtime bundle selection (`INVENTARIO_FRONTEND={legacy|new}`) is wired separately in #1401, and the cutover (delete Vue tree, rename `frontend-react/` → `frontend/`) is tracked in #1423.

This PR ships only the empty house — features land in subsequent sub-issues.

## What's in here

**Frontend (`frontend-react/`)**

- Vite 8 + TS strict (project refs: `app` / `node` / `vitest`) + Tailwind v4 via `@tailwindcss/vite`
- shadcn/ui (`new-york` style, `neutral` base) via `components.json`; locked to the `radix-ui` umbrella, `@base-ui/react` intentionally absent
- `lucide-react`, `class-variance-authority`, `clsx`, `tailwind-merge`, `cmdk`, `tw-animate-css`
- `react-hook-form` + `@hookform/resolvers` + `zod`, `sonner`
- Tiny custom `ThemeProvider` (drops the `next-themes` dep — we're not pretending to be Next.js)
- `@theme` + OKLCH tokens copied 1:1 from [`denisvmedia/inventario-design`](https://github.com/denisvmedia/inventario-design) — that repo is canonical for the visual contract
- ESLint flat config (TS + React + react-hooks + jsx-a11y) + Prettier; ESLint 9 (the React plugin ecosystem hasn't fully caught up to ESLint 10 — Renovate will handle the bump)
- Vitest + `@testing-library/react` + `@testing-library/user-event` + `jsdom` + `jest-axe`; coverage report via `@vitest/coverage-v8` (no minimum gate yet — the epic-level 80% gate is enforced over time)
- Hello-world `HomePage` + a 2-test smoke spec (render + axe)
- `index.html` is clean: `Inventario` title, no Bolt `og:image` / `twitter:image`, no `.bolt/` directory

**Go embed**

- `frontend-react/frontend.go` mirrors `frontend/frontend.go`: under `//go:build with_frontend` it exposes `frontendreact.GetDist()` via `//go:embed all:dist`
- `frontend-react/go.mod` is a peer module wired through `go/go.mod` `require` + `replace` (same pattern as the legacy bundle)
- `go/apiserver/frontend_react_embed_test.go` reads `dist/index.html`, asserts the title is exactly `Inventario`, asserts no `Design Proposal` / `bolt.new` artifacts, and walks `dist/assets` for embed sanity

**Make**

- New targets: `build-frontend-react`, `lint-frontend-react`, `test-frontend-react`, `test-frontend-react-coverage`, `typecheck-frontend-react`, `run-frontend-react`
- Wired into combined targets: `make test`, `make lint`, `make clean`, `make deps`

**Docker**

- New `frontend-react-builder` stage parallel to `frontend-builder`
- `go-base` copies both `dist/` directories so `with_frontend` builds find both bundles

**CI**

- `frontend-react-lint.yml` — typecheck + ESLint + Prettier check on every PR
- `frontend-react-test.yml` — Vitest with coverage + production build on every PR
- `frontend-react-embed-smoke-test.yml` — builds the bundle, then runs the Go embed test under `-tags with_frontend`
- No path filters on any of the three (per the project convention — PR-train branches need full coverage)

## Layout

```
frontend-react/
├── public/favicon.svg
├── src/
│   ├── app/App.tsx
│   ├── components/
│   │   ├── theme-provider.tsx
│   │   └── ui/button.tsx
│   ├── features/        (.gitkeep — feature slices land later)
│   ├── hooks/           (.gitkeep)
│   ├── i18n/            (.gitkeep — react-i18next bootstrap is #1405)
│   ├── lib/utils.ts     (cn helper)
│   ├── pages/
│   │   ├── Home.tsx
│   │   └── Home.test.tsx
│   ├── test/setup.ts    (jest-dom + jest-axe wiring + RTL cleanup)
│   ├── types/           (.gitkeep — OpenAPI codegen is #1403)
│   ├── index.css        (Tailwind v4 + @theme + :root / .dark tokens)
│   ├── main.tsx
│   └── vite-env.d.ts
├── frontend.go
├── go.mod
├── components.json
├── eslint.config.js
├── tsconfig.{json,app,node,vitest}.json
├── vite.config.ts
├── vitest.config.ts
├── index.html
├── package.json
└── README.md
```

## Acceptance criteria (from #1402)

- [x] `npm install && npm run build` produces `dist/` with the React 19 bundle
- [x] `npm run typecheck`, `npm run lint`, `npm run test` all pass
- [x] Hello-world page loads at `/` (`vite preview` confirmed locally)
- [ ] `INVENTARIO_FRONTEND=new` Go server serves the React bundle — gated on #1401 (out of scope here)
- [x] `tsconfig` strict, ESLint flat config has the listed plugins, Prettier integrated
- [x] No Bolt.new artifacts (asserted by the Go embed test)
- [x] Make targets work: `make lint-frontend-react`, `make test-frontend-react`, `make build-frontend-react`
- [x] Coverage report generated on `npm run test:coverage`
- [x] CI runs the new targets on every PR

## Test plan

- [x] `npm install` clean (559 packages, 0 vulns)
- [x] `npm run typecheck` — clean
- [x] `npm run lint` — clean
- [x] `npm run format:check` — clean
- [x] `npm run test` — 2/2 pass (render + axe a11y)
- [x] `npm run test:coverage` — coverage report generated
- [x] `npm run build` — `dist/index.html`, `assets/index-*.css` (18 kB), `assets/index-*.js` (223 kB)
- [x] `go test -tags with_frontend -run TestFrontendReactEmbed ./apiserver/...` — both pass
- [x] Legacy `go test -tags with_frontend -run TestFrontendEmbed ./apiserver/...` — still passes (no regression)
- [x] `go vet ./apiserver/...` and `go vet -tags with_frontend ./apiserver/...` — clean

## Out of scope

- HTTP client / TanStack Query / OpenAPI codegen — #1403
- Router + auth / group context — #1404
- react-i18next bootstrap — #1405
- App shell (sidebar, top bar, theme/density/mode toggles) — #1406
- All feature pages (#1407–#1416)
- "Coming soon" stubs aggregator — #1417
- Vitest coverage gates + a11y assertions on every component — #1418
- Playwright e2e port — #1419
- Bundle-size / Lighthouse CI gates — #1420
- Dual-bundle env-var handler in Go — #1401
- Cutover (delete `frontend/`, rename `frontend-react/` → `frontend/`) — #1423

### CODE REVIEW

File: frontend-react/README.md [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+The new Inventario web client, built in React 19 + TypeScript + Vite + Tailwind v4 + shadcn/ui.
+
+This tree coexists with the legacy Vue frontend at `frontend/` until the React rewrite reaches feature parity. See epic [#1397](https://github.com/denisvmedia/inventario/issues/1397) for the full plan; this scaffold ships the empty house — subsequent issues fill in features.
+
+## Stack
+
+| Layer | Choice |
+|---|---|
+| Framework | React 19 + TypeScript (strict) |
+| Build | Vite 7 + `@tailwindcss/vite` |
```
[the remark this answers is not in the document]
Comment (denisvmedia) [reply frontend-react/README.md]: Good catch — fixed in 7b3c69b (README updated to Vite 8 to match `package.json`). The mock pins Vite 7; we deliberately tracked the legacy `frontend/` bump to 8.0.10 instead, but the README still had the old number. Thanks!

File: frontend-react/src/components/theme-provider.tsx [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+    root.classList.remove("light", "dark")
+
+    const resolved =
+      theme === "system"
+        ? window.matchMedia("(prefers-color-scheme: dark)").matches
+          ? "dark"
+          : "light"
+        : theme
+
+    root.classList.add(resolved)
```
[the remark this answers is not in the document]
Comment (denisvmedia) [reply frontend-react/src/components/theme-provider.tsx]: Valid — fixed in 7b3c69b. The effect now subscribes to `prefers-color-scheme` via `mql.addEventListener("change", …)` while `theme === "system"` and cleans up on theme change / unmount, so the `.dark` class flips at runtime when the OS appearance changes (matches the `next-themes` behavior we replaced).

**Comment by denisvmedia** [comment]
Re: the Copilot low-confidence note about Docker `node:25.9.0-alpine` vs volta `24.14.1` — addressed in the latest commit. The Dockerfile comment claimed both should match, but a renovate-only bump in c571852 had moved Docker to 25.9.0 while volta stayed on 24.14.1 (LTS). Both builder stages now pin `node:24.14.1-alpine`, aligning Docker with volta + engines + the `.github/actions/vars` action used by every CI lane. When the project deliberately moves to 25.x, all four sources should bump together.

**Comment by denisvmedia** [comment]
### E2E status — pre-existing master breakage, not a regression from this PR

All three browsers fail at `e2e/tests/includes/auth.ts:71`:

```
TimeoutError: page.waitForSelector('input[type="email"]', { timeout: 10000 })
```

Server logs show the legacy Vue bundle is being served correctly (200 on `/login`, all chunks 200 OK including `index-ugK9hPWi.js`, `_plugin-vue_export-helper-DSZ7Ymws.js`, `rolldown-runtime-lhHHWwHU.js`), but the app never renders the login form — webkit/firefox/chromium all give up after the 10s selector timeout.

**Same failure mode as PR #1366** (Vite 8.0.10 bump): https://github.com/denisvmedia/inventario/actions/runs/24977953022 — `tests/commodity-simple-crud.spec.ts:61:3 › fast-fail debug` failing on all 3 browsers with `auth.ts:71` timeout on 2026-04-27. PR #1366 merged into master as `a57a9f3` on 2026-04-28; master's e2e workflow has not run since `f0dac28` (2026-04-26 19:42, the commit before the bump landed), so the breakage was never caught on master.

This PR's diff inherits the broken legacy bundle but does not change anything in `frontend/`. Suggest either:

1. Revert #1366 on master and let renovate retry the Vite 8 bump with a real fix
2. Open a separate issue to debug the Vite 8 + Vue 3 + rolldown-runtime regression — likely something in the new chunk graph (or plugin-vue@6) breaks Vue's mounting on `/login`

Either way, #1402 itself is clean — all unit tests, lint, typecheck, embed smoke tests, the Smoke Test, the Docker build, etc. are green. Happy to leave the e2e check failing here until master is unblocked.

**Comment by denisvmedia** [comment]
### Vite 8 e2e regression — root-caused and fixed in 81dd98d

**Root cause.** Vite 8.0.x silently switched the default bundler from rollup to **rolldown** (the Rust bundler). `rolldown@1.0.0-rc.16` mis-handles cross-chunk symbol hoisting: the Lucide icon factory ends up referenced as `P` in `router-*.js` without a matching `import` line, so the chunk throws `TypeError: P is not a function` at module init. Vue never mounts and every Playwright spec fails at `auth.ts:71` waiting for `input[type="email"]`.

**Reproduction (headless probe against `vite preview`):**
- Vite 8.0.10 build: `pageerror: TypeError: P is not a function (router-BbQS4GPc.js:2:775)` → `input[type="email"]` count = 0
- Inspection of the chunk:
  ```js
  // router-BbQS4GPc.js — imports
  import {n as ce, w as le, wt as X, xn as Z, yt as ue} from "./index-ugK9hPWi.js";
  // …no `P` imported anywhere…
  var de = P(`file-box`, [...]);  // ← P referenced but never defined
  ```
- Vite 7.3.2 build: no console errors, Vue mounts, `input[type="email"]` count = 1.

**Fix.** Pin `frontend/package.json` `vite` to `7.3.2` (last 7.x release). 463/463 vitest specs still pass; lint shows pre-existing warnings only.

When Vite/rolldown ship a fix for cross-chunk symbol hoisting, the bump can be tried again — the next renovate Vite-8 PR should not merge until the full e2e suite is green on it. Worth filing a tracker issue to remember.

**Comment by denisvmedia** [comment]
### CI fully green on e89194a — PR ready for review

All 23 functional checks pass, including the previously failing E2E suite across all three browsers:

| Check | Result |
|---|---|
| E2E Tests (chromium) | ✅ 7m48s |
| E2E Tests (firefox) | ✅ 8m51s |
| E2E Tests (webkit) | ✅ 8m49s |
| embed smoke test (legacy) | ✅ 1m3s |
| embed smoke test (React) | ✅ 44s |
| Build × 3 platforms, Smoke, Kind smoke, goreleaser | ✅ |
| Lint / Test / typecheck for both bundles | ✅ |

Two unplanned fixes shipped alongside the scaffold itself, both rooted in the Vite 8.0.10 renovate bump (#1366) that landed on master 2026-04-28:

1. `frontend/package.json` pinned to `vite@7.3.2` — Vite 8 silently switched the default bundler to **rolldown**, which mis-handled cross-chunk symbol hoisting and broke the legacy Vue bundle (`TypeError: P is not a function` in `router-*.js`, Vue never mounted, login form never rendered, every Playwright spec failed at `auth.ts:71`). Pinning back to Vite 7 with rollup restores the working build. Verified locally with a headless probe + the full e2e suite in CI.
2. `go/apiserver/frontend_embed_test.go` made bundler-agnostic — Vite 7's rollup output doesn't naturally produce underscore-prefixed chunks the way rolldown did, so the test now relies on a stable marker file at `frontend/public/_inventario-embed.txt` (Vite copies `public/` verbatim into `dist/`). The test still asserts at least one underscore-prefixed file exists in the embedded FS to guard against `//go:embed` losing the `all:` prefix.

Worth filing a follow-up tracker so the next renovate Vite 8 bump doesn't merge until rolldown ships a fix for cross-chunk symbol hoisting (or the project deliberately opts back to rollup).
